pipeline {
    agent any

    tools {
        go 'go1.22.0'
    }

    stages {
         stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'khushi_cred', url: 'https://github.com/OT-MyGurukulam/employee-api.git'
            }
        }
        stage('Code Compilation') {
            steps {
                script {
                    sh 'go install'
                    sh "go list -f '{{.Target}}'"
                }
            }
        }
    }
}
