pipeline {
    agent any
    
    tools {
        // Define the Go tool installation named 'Go' using the configured path
        go 'go1.22.0'
    }
    
    stages {
        stage('Checkout') {
            steps { 
                git branch: 'main', credentialsId: 'khushi_cred', url: 'https://github.com/OT-MyGurukulam/employee-api.git'
            }
        }
        stage('Code Compilation') {
            steps {
                script {
                    // Use the 'go' tool to run Go commands
                    sh 'go install' 
                    sh "go list -f '{{.Target}}'"
                }
            }
        }
    }
}
