pipeline {
    agent any

    tools {
       maven 'mvn'
    }

    stages {
        stage("Git Checkout") {
            steps {
                script {
                    git branch: 'main', url: 'https://github.com/shreya0522/salary-api.git'
                }
            }
        }
        stage ('Compile'){
            steps{
                sh 'mvn clean compile'
                }
        }

        stage('Static Code Analysis') {
            steps {
                withSonarQubeEnv(installationName: 'sq1') { 
                    sh './mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar'
                }
            }
        }
    }
}
