pipeline {
    agent any

    tools {
       maven 'mvn'
    }

    stages {
        stage("Git Checkout") {
            steps {
                script {
                    git branch: 'main', url: 'https://github.com/OT-MICROSERVICES/salary-api.git'
                }
            }
        }
        stage ('compile'){
            steps{
                sh 'mvn clean compile'
                }
        }

        stage('Static Code Analysis') {
            steps {
                withSonarQubeEnv(installationName: 'sq1') { 
                    sh './mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar'
                }
            }
        }
    }
    post {
        always {
        // One or more steps need to be included within each condition's block.
        cleanWs cleanWhenSuccess: false
       }
        success { 
            echo 'Build Successfully !'
        }
        failure { 
            echo 'Build Failed !'
        }
    }
}
