@Library('p7-shared-library') _
def ansible_CD = new org.avengers.template.ansible_CD.ansibleCD()
pipeline {
    agent any
    

    stages {
        stage ('Scylla CD'){
            steps{
                script{
    def url = 'https://github.com/CodeOps-Hub/Ansible.git'
    def creds = 'harshit-github-token'
    def branch = 'main'
    // def gitleaksVersion = '8.18.2'
    def path = './scylla.yml'
    
    // ansible_CD.call(url, creds, branch, gitleaksVersion, path)
        ansible_CD.call(url, creds, branch, path)
                }
            }
             
        }
    }
}
