@Library('snaatak-p7') _
def BugsAnalysis = new org.avengers.template.python.PythonBugsAnalysis

node {
    
    def url = 'https://github.com/CodeOps-Hub/attendance-api.git'
    def creds = '890c8a72-7383-4986-8573-519aacdeb7d2'
    def branch = 'main'
       
    dast.call(url, creds, branch)
    
}
