@Library('shared-library') _


pipeline {
    agent any
    
    tools {
        // Define the Go tool installation named 'Go' using the configured path
        go 'go1.22.0'
    }
    
    stages {
        stage('Setup') {
            steps {
                git branch: 'main', credentialsId: 'Khushi-malhoz-PAT', url: 'https://github.com/avengers-p7/Jenkinsfile.git'
            }
        }
        
        stage('Code Compilation') {
            steps {
                golangCodeCompilation()
            }
        }
    }
}
