@Library('shared-library') _
def golangcodecompilation = new org.avengers.template.golang.GolangCodeCompilation()

node {
    
    def url = 'https://github.com/OT-MICROSERVICES/employee-api.git'
    def creds = 'khushi09'
    def branch = 'main'
    
    golangcodecompilation.call(url, creds, branch)
    
}
