pipeline {
    agent any

    stages {
         stage('Checkout SCM') {
            steps {
                    git branch: 'main', url: 'https://github.com/OT-MICROSERVICES/salary-api.git'
            }
        }
        
        stage('Download and Install Gitleaks') {
            steps {
                    sh 'wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz'
                    // Extract Gitleaks
                    sh 'tar xvzf gitleaks_8.18.2_linux_x64.tar.gz'
            }
        }
        

        stage('Gitleaks Scan') {
            steps {
                    sh './gitleaks detect -r credScanReport'
            }
        }
    }
    post {
        success {
            cleanWs()
        }
        failure {
            archiveArtifacts artifacts: '**/credScanReport'
            cleanWs()
        }
    }
}
