pipeline {
    agent any
    tools {
      maven 'mvn'
    }
    stages {
        stage('Checkout GIT') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Panu-S-Harshit-Ninja-07/OT-Salary-API.git']])
                sh 'ls $WORKSPACE/'
            }
        }
        stage('Starting Code Compilation ') {
            steps {
                sh 'echo "Starting Java Code Compilation.........."'
                sh 'mvn clean compile'
            }
        }
    }
post {
        always {
        // One or more steps need to be included within each condition's block.
        cleanWs cleanWhenSuccess: false
       }
        success { 
            sh 'ls $WORKSPACE/'
            echo 'Compiled Successfully !'
            sh 'tree $WORKSPACE/target/'
        }
        failure { 
            echo 'Compilation Failed !'
        }
    }
}
