@Library('my-shared-library') _
def ansible_CD = new org.avengers.template.ansible_CD.ansibleCD()

node {
    
    def url = 'https://github.com/CodeOps-Hub/scyllaDB-ansible-role.git'
    def creds = 'SnaatakID'
    def branch = 'main'
    def gitleaksVersion = '8.18.2'
    def path = '/var/lib/jenkins/workspace/Ansible_CD/jenkins_playbook/install_debian.yml'
    
    ansible_CD.call(url, creds, branch, gitleaksVersion, path)
    
}
