pipeline {
    agent any
    stages {
        stage('GIT Checkout') {
            steps {
                checkout scmGit(branches: [[name: 'vikram/Frontend-node-exp']], extensions: [], userRemoteConfigs: [[credentialsId: 'vikram github token', url: 'https://github.com/CodeOps-Hub/Ansible.git']])
            }
        }
        stage('ansible inventory') {
            steps {
                sh 'ansible --version'
                sh 'ansible-inventory --graph'
            }
        }
        stage('Run Ansible') {
            steps {
                sh 'ansible --version'
                sh 'ansible-playbook --private-key /var/lib/jenkins/snaatak.pem salary-node-exporter.yml'
            }
        }
    }
}
