pipeline {
    agent any
    stages {
        stage('GIT Checkout') {
            steps {
                checkout scmGit(branches: [[name: 'vikram/Frontend_Node_exp']], extensions: [], userRemoteConfigs: [[credentialsId: '053aa239-b1c0-437d-a686-940941d1eae0', url: 'https://github.com/CodeOps-Hub/Ansible.git']])
            }
        }
        stage('ansible inventory') {
            steps {
                sh 'ansible --version'
                sh 'ansible-inventory --graph'
            }
        }
        stage('Run Ansible') {
            steps {
                sh 'ansible --version'
                sh 'ansible-playbook --private-key /var/lib/jenkins/snaatak.pem playbook.yml'
            }
        }
    }
}
