@Library("my-shared-library") _

def credScan  = new org.avengers.template.genericCi.CredScan()

node {
    
    def url = 'https://github.com/CodeOps-Hub/Employee-API.git'
    def branch = 'main'
    def gitLeaksVersion = '8.18.2'
    def reportName = 'credScanReport.json'
    
   credScan.call(branch: branch,url: url, gitLeaksVersion, reportName)
    
}
