@Library('my-shared-library') _

def asg = new org.avengers.asg_tfmodule_CICD.asgCICD()

pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials('samir_aws_creds')
        AWS_SECRET_ACCESS_KEY = credentials('samir_aws_creds')
        TF_CLI_ARGS = '-input=false'
    }
    
    parameters {
        string(name: 'branch', defaultValue: 'main', description: 'Enter the branch name')
        string(name: 'rootPath', defaultValue: 'Modules', description: 'Enter the root directory path')
        string(name: 'childPath', defaultValue: 'Auto_Sacling_Module', description: 'Enter the child directory path')
        string(name: 'tagVersion', defaultValue: 'null', description: 'Enter the correct version')
        string(name: 'gitpath', defaultValue: 'null', description: 'Enter the correct version')
    }
    
    stages {
        stage('Terraform') {
            steps {
                script {
                    def url = 'https://github.com/CodeOps-Hub/Terraform-modules.git'
                    def creds = 'cfb1a43a-bdbe-4b72-9966-6f42f75e98b1'
                    
                    asg.call(params.rootPath, params.childPath, params.branch, params.gitpath)
                }
            }
        }
    }
}
