@Library("my-shared-library") _
pipeline {
    agent any

    stages {
        stage('GIT Checkout') {
            steps {
                gitCheckout(branch: "main", url: "https://github.com/Parasharam-DevOps/salary-api.git"  )

            }
        }
        stage('Compile'){
            steps{
                javaUnitTesting()
            }
        }
    }
post {
        always {
        // One or more steps need to be included within each condition's block.
        cleanWorkspace()
       }
        success { 
            echo 'Job Run Successfully !'
        }
        failure { 
            echo 'Job Failed !'
        }
    }
}
