@Library("my-shared-library") _

def unitTesting = new org.avengers.template.java.javaUnitTesting()

node {
    
    def url = 'https://github.com/Parasharam-DevOps/salary-api.git'
    def branch = 'main'
    
    unitTesting.call(branch: branch,url: url)
    
}
