@Library('my-shared-library') _

pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Call the checkoutStage function from the shared library
                    javaUnitTesting.checkoutStage()
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    // Call the testStage function from the shared library
                    javaUnitTesting.testStage()
                }
            }
        }
    }
}
