@Library('dast_sharedLib') _
def dast = new org.avengers.template.java.javaDast()

node {
    
    def url = 'https://github.com/CodeOps-Hub/Salary-API.git'
    def creds = 'vyadavP7'
    def branch = 'main'
    def zapVersion = '2.14.0'
    def currentWorkspace = env.WORKSPACE 
        
    dast.call(url, creds, branch, zapVersion)
    
}
