@Library('terragrunt_sharedLib@Vidhi/terragrunt-sharedlib') _

def terragrunt = new org.avengers.template.terragrunt.terragrunt()
properties([
    parameters([
        choice(name: 'branch', choices: ['Vidhi/network-skeleton-QA'], description: 'Select the branch'),
        choice(name: 'rootPath', choices: ['network-skeleton'], description: 'Select the root directory'),
        choice(name: 'childPath',choices: ['dev'], description: 'Select the child directory'),
    ])
])
node {
    def url = 'git@github.com:CodeOps-Hub/Terragrunt.git'
    def creds = 'new-token'


    terragrunt.call(url, creds, params.branch, params.rootPath, params.childPath)
     
}
