@Library("my-shared-library") _

def genericCiPackerAmi = new org.avengers.template.genericCi.GenericCiAmi()

node {
    
    def url = 'https://github.com/CodeOps-Hub/AMI.git'
    def creds = 'c78ea501-f75a-4296-8f25-05a43fb2b116'
    def branch = 'main'
    
    genericCiPackerAmi.call(url, creds, branch)
    
}
