@Library("my-shared-library") _

def staticCodeAnalysis = new org.avengers.template.java.staticCodeAnalysis()

node {
    
    def url = 'https://github.com/OT-MICROSERVICES/salary-api.git'
    def branch = 'main'
    
    staticCodeAnalysis.call(branch: branch,url: url)
    
}
