pipeline {
    agent any
    // environment {
        // ANSIBLE_PRIVATE_KEY = credentials('vd-key')
    // }
    stages {
        stage('GIT Checkout') {
            steps {
                checkout scmGit(branches: [[name: 'Vidhi/node-exporter-Scylla']], extensions: [], userRemoteConfigs: [[credentialsId: 'harshit-github-token', url: 'git@github.com:CodeOps-Hub/Ansible.git']])
            }
        }
        stage('ansible inventory') {
            steps {
                sh 'ansible --version'
                sh 'ansible-inventory --graph'
            }
        }
        // stage('Run Ansible') {
        //     steps {
        //         sh 'ansible --version'
        //         sh 'ansible-playbook -i aws_ec2.yaml --private-key=$ANSIBLE_PRIVATE_KEY scylla_node_exporter.yml'
        //     }
        // }
    }
}
