pipeline {
    agent any
    stages {
        stage('GIT Checkout') {
            steps {
                checkout scmGit(branches: [[name: 'aakash/frontend-dashboard']], extensions: [], userRemoteConfigs: [[credentialsId: 'harshit-github-token', url: 'https://github.com/CodeOps-Hub/Ansible.git']])
            }
        }
        stage('ansible inventory') {
            steps {
                sh 'ansible --version'
                sh 'ansible-inventory --graph'
            }
        }
        stage('Run Ansible') {
            steps {
                sh 'ansible --version'
                sh 'ansible-playbook frontend-dashboard.yml'
            }
        }
    }
}
