node {
    stage('Build') {
        // Define the DSL for creating a Freestyle job
        def jobDSL = '''
            job('Freestyle-Job') {
                description('This is a sample Freestyle job created using a Scripted Pipeline')
                steps {
                    shell('echo "Hello, world!"')
                }
            }
        '''
        // Execute the job DSL to create the Freestyle job
        jobDsl scriptText: jobDSL
    }
}

try {
    // Execute this block if the build succeeds
    stage('Notify Success') {
        // Send Slack notification for success
        slackSend channel: 'jenkinss', message: 'Job Build successfully'
    }
} catch (Exception e) {
    // Execute this block if the build fails
    stage('Notify Failure') {
        // Send Slack notification for failure
        slackSend channel: 'jenkinss', message: 'Job Failed '
    }
}
