@Library("unitTesting-python-library") _

def unitTesting = new org.avengers.template.python.javaUnitTesting()

node {
    
    def url = 'https://github.com/CodeOps-Hub/Attendance-API.git'
    def branch = 'main'
    
    unitTesting.call(branch: branch,url: url)
    
}
