pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/CodeOps-Hub/Salary-API.git'
            }
        }
        stage('Owasp DP-Check') {
            steps {
                // Run DP-Check
                dependencyCheck additionalArguments: '--scan target/ --format ALL', odcInstallation: 'DP-check'
            }
        }
        stage('Package Artifacts') {
            steps {
                sh 'mvn clean package -DskipTests=true'
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: '**/dependency-check-report.html'
            sh "ls $WORKSPACE/"
            echo 'DP check Successfull !'
            sh 'tree $WORKSPACE/'
        }
        failure {
            echo 'DP check Failed !'
        }
    }
}
