@Library("my-shared-library") _

def javaCodeCompile = new org.avengers.template.java.javaCodeCompilation()

node {
    
    def url = 'https://github.com/OT-MICROSERVICES/attendance-api.git'
    def branch = 'main'
    
    javaCodeCompilation.call(url, branch)
    
}
