@Library("my-shared-library") _
pipeline {
    agent any

    stages {
        stage('GIT Checkout') {
            steps {
                gitCheckout(branch: "main", url: "https://github.com/Panu-S-Harshit-Ninja-07/OT-Salary-API.git"  )

            }
        }
        stage('Compile'){
            steps{
                javaCodeCompilation()
            }
        }
    }
post {
        always {
        // One or more steps need to be included within each condition's block.
        cleanWorkspace()
       }
        success { 
            echo 'Compiled Successfully !'
        }
        failure { 
            echo 'Compilation Failed !'
        }
    }
}
