@Library('my-shared-library@Vidhi/terragrunt-sharedlib') _

def terragrunt = new org.avengers.template.terragrunt.terragrunt()
properties([
    parameters([
        choice (choices: ['apply', 'destroy'], name: 'action', description: 'Choose Terragrunt ACTION to perform'),
        string (defaultValue: 'harshit/PostgreSQL-dev', description: '', name: 'branch'),
        string (defaultValue: 'Database/PostgreSQL', description: 'define path of root directory', name: 'rootPath'),
        string (defaultValue: 'dev', description: 'define path of child directory', name: 'childPath'),
    ])
])
node {
    def url = 'git@github.com:CodeOps-Hub/Terragrunt.git'
    def creds = 'Harshit-Github-PAT'

withAWS(credentials: 'HARSHIT_AWS_CREDS') {
                        terragrunt.call(url, creds, params.branch, params.rootPath, params.childPath, params.action)
}
     
}

