@Library('p7-shared-library@Vidhi/terragrunt-sharedlib') _

def terragrunt = new org.avengers.template.terragrunt.terragrunt()
properties([
    parameters([
        choice (choices: ['apply', 'destroy'], name: 'operation', description: 'Choose Terragrunt operation to perform'),
        string (defaultValue: 'harshit/PostgreSQL-dev', description: '', name: 'repoBranch'),
        string (defaultValue: 'Dev', description: 'Define path of root directory', name: 'environment'),
        string (defaultValue: 'PostgreSQL', description: 'Define path of child directory', name: 'service'),
    ])
])
node {
    def url = 'https://github.com/CodeOps-Hub/Terragrunt.git'
    def creds = 'harshit-github-token'

    terragrunt.call(url, creds, params.repoBranch, params.environment, params.service, params.operation)
}
