@Library('snaatak-p7') _

pipeline {
    agent any
    
    stages {
        stage('Install Go') {
            steps {
                script{
                    golangUnitTesting.installgo()
                }
            }
        }
        stage('Checkout') {
            steps {
                gitCheckoutPrivate(branch: 'main', url: 'https://github.com/OT-MICROSERVICES/employee-api.git', credentialsId: 'vishal-cred')
            }
        }
        stage('Testing') {
            steps {
                script{
                    golangUnitTesting.testing()
                }
            }
        }
        stage('Generate HTML Report') {
            steps {
                script{
                    golangUnitTesting.html()
                }
            }
        }
    }
}
    
        
