@Library('snaatak-p7') _
def golangBugAnalysis = new org.avengers.template.GolangBugAnalysis()

node {
    
    def url = 'https://github.com/OT-MICROSERVICES/employee-api.git'
    def creds = 'vishal-cred'
    def branch = 'main'
    
    golangUnitTesting.call(url, creds, branch)
    
}
