@Library('terragrunt_sharedLib@Vidhi/terragrunt-sharedlib') _

def terragrunt = new org.avengers.template.terragrunt.terragrunt()
properties([
    parameters([
        string(name: 'branch', defaultValue: 'Vidhi/network-skeleton-QA', description: 'Select the branch'),
        string(name: 'rootPath', defaultValue: 'network-skeleton', description: 'Select the root directory'),
        string(name: 'childPath', defaultValue: 'QA', description: 'Select the child directory'),
        choice(name: 'executeDestroy', choices: ['Yes', 'No'], description: 'Select action'),
    ])
])
node {
    def url = 'git@github.com:CodeOps-Hub/Terragrunt.git'
    def creds = 'new-token'


    terragrunt.call(url, creds, params.branch, params.rootPath, params.childPath, params.executeDestroy)
     
}
