node {
    // Checkout SCM
    stage('Checkout SCM') {
        git branch: 'main', url: 'https://github.com/OT-MICROSERVICES/employee-api.git'
    }

    // Download and Install Gitleaks
    stage('Download and Install Gitleaks') {
        sh 'wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz'
        sh 'tar xvzf gitleaks_8.18.2_linux_x64.tar.gz'
    }

    // Gitleaks Scan
    stage('Gitleaks Scan') {
         try {
            sh './gitleaks detect -r credScanReport'
        } catch (Exception e) {
            echo "Gitleaks scan failed. Archiving report."
            archiveArtifacts artifacts: 'credScanReport', allowEmptyArchive: true
            error 'Gitleaks scan failed'
        }
    }

    // Post-build actions
    cleanWs()

}

