pipeline {
    agent any
    environment {
        ANSIBLE_PRIVATE_KEY = credentials('vd-key')
    }
    stages {
        stage('GIT Checkout') {
            steps {
                script {
                    // Checkout the repository
                    checkout scmGit(
                        branches: [[name: 'Vidhi/Kibana-dashboard-role']],
                        extensions: [],
                        userRemoteConfigs: [[credentialsId: 'github-new-token', url: 'https://github.com/CodeOps-Hub/Ansible.git']]
                    )

                    // Run git remote prune
                    sh 'git remote prune origin'
                }
            }
        }
        stage('ansible inventory') {
            steps {
                sh 'ansible --version'
                sh 'ansible-inventory --graph'
            }
        }
        stage('Run Ansible') {
            steps {
                sh 'ansible --version'
                sh 'ansible-playbook --private-key=$ANSIBLE_PRIVATE_KEY kibana_dashboard.yml'
            }
        }
    }
}
