pipeline {
    agent any
    stages {
        stage('GIT Checkout') {
            steps {
                checkout scmGit(branches: [[name: 'vishal/employee-node-exp']], extensions: [], userRemoteConfigs: [[credentialsId: 'vishal-PAT', url: 'https://github.com/CodeOps-Hub/Ansible.git']])
            }
        }
        stage('ansible inventory') {
            steps {
                sh 'ansible --version'
                sh 'ansible-inventory --graph'
            }
        }
        stage('Run Ansible') {
            steps {
                sh 'ansible-playbook --private-key /var/lib/jenkins/snaatak.pem employee.yml'
            }
        }
    }
}
