node {
    // Cleanup Workspace
    cleanWs()

    // Clone Repository
    stage('Clone Repository') {
        git branch: 'main', url: 'https://github.com/vyadavP7/Salary-API.git'
    }
  
    stage('Package Artifacts') {
        sh 'mvn clean package -DskipTests=true'
    }

    // Owasp DP-Check
    stage('Owasp DP-Check') {
        dependencyCheck additionalArguments: '--scan target/ --format ALL', odcInstallation: 'DP-check'
        archiveArtifacts artifacts: '**/dependency-check-report.html'
    }
}
