@Library('my-shared-library') _
def ansibleRole_CD = new org.avengers.template.ansibleRole_CD.ansibleRoleCD()

node {
    
    def url = 'https://github.com/CodeOps-Hub/scyllaDB-ansible-role.git'
    def creds = 'SnaatakID'
    def branch = 'main'
    def gitleaksVersion = '8.18.2'
    def tagVersion = '1.2'
    def path  = "/var/lib/jenkins/workspace/SharedLiabrary_CICD/scylla-ansible-role/tests/test.yml"
    def gitpath = 'CodeOps-Hub/scyllaDB-ansible-role.git'

    
    ansibleRole_CD.call(url, creds, branch, gitleaksVersion, tagVersion, path, gitpath)
    
}
