@Library('snaatak-p7') _
def ansibleRole_CD = new org.avengers.template.ansibleRole_CD.ansibleRoleCD()

node {
    
    def url = 'https://github.com/CodeOps-Hub/Jenkins-Playbook.git'
    def creds = '890c8a72-7383-4986-8573-519aacdeb7d2'
    def branch = 'main'
    def gitleaksVersion = '8.18.2'
    def tagVersion = '1.0'
    
    ansibleRole_CD.call(url, creds, branch, gitleaksVersion)
    
}
