pipeline {
    agent any
    tools {
        go 'go1.22.0'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'khushi_cred', url: 'https://github.com/OT-MyGurukulam/employee-api.git'
            }
        }
        stage('Build') {
            steps {
                sh 'go build'
            }
        }
        stage('Test') {
            steps {
                script {
                    writeFile file: 'test_my_function_test.go', text: '''
                        package main
                        import (
                            "testing"
                        )
                        func TestMyFunction(t *testing.T) {
                        }
                    '''
                }
                sh 'go test ./...'
            }
        }
        stage('SonarQube Analysis') {
            steps {
               // withSonarQubeEnv('sq1') {
               //     script {
                //        def scannerHome = tool 'sonar-scanner'
                //        withEnv(["/opt/sonarqube/sonarqube-9.6.1.59531/bin/linux-x86-64/sonar.sh=${scannerHome}/bin"]) {
                 //           sh 'sonar-scanner'
                      withSonarQubeEnv('sq1') {
                        sh '/opt/sonarqube/sonarqube-9.6.1.59531/bin/sonar-scanner -Dsonar.projectKey=sqp_eea3e72ff557b782be9e7389c0add95a5754b1f9  -Dsonar.sources=.'
                        //  -Dsonar.organization=wm1 
                        //  -Dsonar.projectKey=sqp_eea3e72ff557b782be9e7389c0add95a5754b1f9
                        //  -Dsonar.sources=. 
                         // -Dsonar.host.url=http://34.130.152.26:9000/  ///sonarcloud.io'
                    }
                        }
                    }
                }
            }
        }
    }
}
