pipeline {
    agent any
    tools {
        go 'go1.22.0'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'khushi_cred', url: 'https://github.com/OT-MyGurukulam/employee-api.git'
            }
        }
        stage('Build') {
            steps {
                sh 'go build'
            }
        }
        // stage('Test') {
        //     steps {
        //         script {
        //             writeFile file: 'test_my_function_test.go', text: '''
        //                 package main
        //                 import (
        //                     "testing"
        //                 )
        //                 func TestMyFunction(t *testing.T) {
        //                 }
        //             '''
        //         }
        //         sh 'go test ./...'
        //     }
        // }
        stage('SonarQube Analysis') {
            steps {

                 withSonarQubeEnv('sq1') {
                        sh "/var/lib/jenkins/tools/hudson.plugins.sonar.MsBuildSQRunnerInstallation/SonarScanner/sonar-scanner-5.0.1.3006/bin/sonar-scanner -Dsonar.projectKey=gloang-static-01 -Dsonar.sources=. -Dsonar.host.url=http://10.188.0.3:9000  -Dsonar.login=sqp_baf01327c387b84a45b8796884f8bdcd2f3c7097"
                    }
                     
                    }
                        }
                    }
                }
    
