
pipeline {
    agent any
    
    stages {
        stage('Installation Go') {
            steps {
                script {
                    // Update apt packages
                    sh 'sudo apt update'
                    // Install Go using snap
                    sh 'sudo snap install go --classic'
                    
                }
            }
        }
        stage('Clone Repository') {
            steps {
                // Clone the Git repository
                git branch: 'main', credentialsId: 'vishal-cred', url: 'https://github.com/OT-MICROSERVICES/employee-api.git'
            }
        }
        stage('Testing') {
            steps {
                script {
                    // Run go test and ignore errors
                    sh 'go test ./... || true'
                }
            }
        }
        stage('Generate HTML Report') {
            steps {
                script {
                    // Run gotest with specify the output format and generate HTML Report
                    sh 'go test ./... -coverprofile=coverage.out || true'
                    sh 'go tool cover -html=coverage.out -o coverage.html || true'
                    
                }
            }
        }
    }
}
