@Library("my-shared-library") _

def genericCiSlackNotification = new org.avengers.genericCi.slackNotification.GenericCiSlackNotification()

node {
    // Assuming you have a variable called buildStatus with either 'SUCCESS' or 'FAILURE'
    genericCiSlackNotification.call(buildStatus)
}


    
    



    
    


