@Library("my-shared-library") _

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Define the DSL for creating a Freestyle job
                    def jobDSL = '''
                        job('My-Freestyle-Job') {
                            description('This is a sample Freestyle job created using a Declarative Pipeline')
                            steps {
                                shell('echo "Hello, world!"')
                            }
                        }
                    '''
                    // Execute the job DSL to create the Freestyle job
                    jobDsl scriptText: jobDSL
                }
            }
        }
    }

    post {
        success { 
            slackNotification("SUCCESS")
            echo 'Compiled Successfully !'
        }
        failure { 
            slackNotification("FAILURE")
            echo 'Compilation Failed !'
        }
    }
}


    
    

    


    
    



    
    


