@Library('my-shared-library') _

def asg = new org.avengers.template.Module_CI_CD.cicd()

pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials('samir_aws_creds')
        AWS_SECRET_ACCESS_KEY = credentials('samir_aws_creds')
        TF_CLI_ARGS = '-input=false'
    }
    
    stages {
        stage('Terraform') {
            steps {
                script {
                    properties([
                        parameters([
                            
                            string(name: 'branch', defaultValue: 'main', description: 'Enter the branch name'),
                            string(name: 'rootPath', defaultValue: 'Modules', description: 'Enter the root directory path'),
                            string(name: 'childPath', defaultValue: 'Auto_Sacling_Module', description: 'Enter the child directory path'),
                            string(name: 'tagVersion', defaultValue: 'null', description: 'Enter the correct version'),
                            string(name: 'gitpath', defaultValue: 'CodeOps-Hub/Terraform-modules.git', description: 'Enter the correct GitHub repository path')
                            ([booleanParam(defaultValue: true, description: 'Run Terraform Action', name: 'RUN_TF_ACTION')
                            booleanParam(defaultValue: true, description: 'Run Terraform Init', name: 'RUN_TF_INIT')
                            booleanParam(defaultValue: true, description: 'Run Terraform Format', name: 'RUN_TF_FMT')
                            booleanParam(defaultValue: true, description: 'Run Terraform Validate', name: 'RUN_TF_VALIDATE')
                            booleanParam(defaultValue: true, description: 'Run Static Code Analysis', name: 'RUN_STATIC_CODE_ANALYSIS')
                            booleanParam(defaultValue: true, description: 'Run Checkov', name: 'RUN_CHECKOV')
                            booleanParam(defaultValue: true, description: 'Run Terraform Plan', name: 'RUN_TF_PLAN')
                            booleanParam(defaultValue: true, description: 'Run Git Tag', name: 'RUN_GIT_TAG')
                              ])
                           
                        ])
                    ])

                    def url = 'https://github.com/CodeOps-Hub/Terraform-modules.git'
                    def creds = 'cfb1a43a-bdbe-4b72-9966-6f42f75e98b1'
                    
                    
                    asg.call(url, creds, params.branch, params.rootPath, params.childPath, params.tagVersion, params.gitpath, params.RUN_TF_ACTION, params.RUN_TF_INIT, params.RUN_TF_FMT, params.RUN_TF_VALIDATE, params.RUN_STATIC_CODE_ANALYSIS, params.RUN_CHECKOV, params.RUN_TF_PLAN, params.RUN_GIT_TAG)
                }
            }
        }
    }
}
