@Library('my-shared-library') _

def asg = new org.avengers.template.Module_CI_CD.cicd()

pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials('samir_aws_creds')
        AWS_SECRET_ACCESS_KEY = credentials('samir_aws_creds')
        TF_CLI_ARGS = '-input=false'
    }
    
    stages {
        stage('Terraform') {
            steps {
                script {
                    properties([
                        parameters([
                            
                            string(name: 'branch', defaultValue: 'main', description: 'Enter the branch name'),
                            string(name: 'rootPath', defaultValue: 'Modules', description: 'Enter the root directory path'),
                            string(name: 'childPath', defaultValue: 'Auto_Sacling_Module', description: 'Enter the child directory path'),
                            string(name: 'tagVersion', defaultValue: 'null', description: 'Enter the correct version'),
                            string(name: 'gitpath', defaultValue: 'CodeOps-Hub/Terraform-modules.git', description: 'Enter the correct GitHub repository path'),
                            booleanParam(defaultValue: true, description: 'Run Terraform Action', name: 'runTerraformAction'),
                            booleanParam(defaultValue: true, description: 'Run Terraform Init', name: 'runTerraformInit'),
                            booleanParam(defaultValue: true, description: 'Run Terraform Format', name: 'runTerraformFmt'),
                            booleanParam(defaultValue: true, description: 'Run Terraform Validate', name: 'runTerraformValidate'),
                            booleanParam(defaultValue: true, description: 'Run Static Code Analysis', name: 'runStaticCodeAnalysis'),
                            booleanParam(defaultValue: true, description: 'Run Checkov', name: 'runCheckov'),
                            booleanParam(defaultValue: true, description: 'Run Terraform Plan', name: 'runTerraformPlan'),
                            booleanParam(defaultValue: true, description: 'Run Git Tag', name: 'runGitTag')
                              
                           
                        ])
                    ])

                    def url = 'https://github.com/CodeOps-Hub/Terraform-modules.git'
                    def creds = 'Harshit-Github-PAT'
                    
                    
                    asg.call(url, creds, params.branch, params.rootPath, params.childPath, params.tagVersion, params.gitpath, params.runTerraformAction, params.runTerraformInit, params.runTerraformFmt, params.runTerraformValidate, params.runStaticCodeAnalysis, params.runCheckov, params.runTerraformPlan, params.runGitTag)
                }
            }
        }
    }
}
