@Library('my-shared-library') _

pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    gitCheckout(branch: "main", url: "https://github.com/Parasharam-Desai/salary-api.git")
                }
            }
        }
        stage('Bug Analysis') {
            steps {
                script {
                    javaBugAnalysis()
                }
            }
        }
        stage('Publish HTML Report') {
            steps {
                script {
                    javaBugHtmlReport()
                }
            }
        }
    }
}
post {
        always {
        // One or more steps need to be included within each condition's block.
        cleanWorkspace()
       }
        success { 
            echo 'Compiled Successfully !'
        }
        failure { 
            echo 'Compilation Failed !'
        }
    }
}
