@Library('my-shared-library') _

pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    javaBugAnalysis.checkoutStage()
                }
            }
        }
        stage('Bug Analysis') {
            steps {
                script {
                    javaBugAnalysis.bugAnalysisStage()
                }
            }
        }
        stage('Publish HTML Report') {
            steps {
                script {
                    javaBugAnalysis.htmlReportStage()
                }
            }
        }
    }
}
