@Library("my-shared-library") _

def javaBugAnalysis = new org.avengers.template.java.javaBugAnalysis()

node {
    
    def url = 'https://github.com/Parasharam-Desai/salary-api.git'
    def branch = 'main'
    
    javaBugAnalysis.call(branch: branch,url: url)
    
}
