@Library('snaatak-p7') _
def dast = new org.avengers.template.golang.GolangDast()


node {
    
    def url = 'https://github.com/OT-MICROSERVICES/employee-api.git'
    def creds = 'Snatak-SamirKesare'
    def branch = 'main'
    def zapVersion = '2.14.0'
    
    dast.call(url, creds, branch, zapVersion)
    
}
