@Library('snaatak-p7') _
def codeAnalysis = new org.avengers.template.python.PythonStaticCodeAnalysis()

node {
    
    def url = 'https://github.com/CodeOps-Hub/attendance-api.git'
    def creds = 'Attendance-creds'
    def branch = 'main'
       
    codeAnalysis.call(url, creds, branch)
    
}
