@Library('shared-library') _
def commitSignOffPipeline = new org.avengers.template.CommitSignOff.CommitSignOffPipeline()

node {
   
    def url = 'https://github.com/orgs/CodeOps-Hub/repositories'
    def creds = 'khushi09'
    def branch = 'main'
    
    golangcodecompilation.call(url, creds, branch)
    commitSignOffPipeline.call()  
    
}
