@Library('shared-library') _

pipeline {
    agent any
    
    stages {
       stage('Checkout GIT') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/khushimalhoz/Shared-library.git']])
            
            }
        }
        stage('Fetch Last Commit') {
            steps {
                // Use the shared library method
                fetchLastCommit()
            }
        }
    }
}
