@Library('shared-library') _
def commitSignOffPipeline = new org.avengers.template.CommitSignOff.CommitSignOffPipeline()

node {
    
    def url = 'https://github.com/CodeOps-Hub/SharedLibrary.git'
    def creds = 'khushi09'
    def branch = 'main'
    
    commitSignOffPipeline.call(url, creds, branch)
    
}
