     node {
         // Define tools
         def mvnHome = tool 'mvn'
     
         // Checkout stage
         stage('Checkout') {
             git branch: 'main', url: 'https://github.com/Parasharam-DevOps/salary-api.git'
         }
     
         // Test stage
         stage('Test') {
             echo "Executing Java Unit Testing"
             sh "${mvnHome}/bin/mvn test"
         }
     }
