    node {
        stage("Git Checkout") {
            git branch: 'main', url: 'https://github.com/Parasharam-Desai/salary-api.git'
        }
        
        stage("Bug Analysis") {
            sh 'mvn compile'
            sh 'mvn spotbugs:spotbugs'
            sh 'mvn site'
        }
        
        stage('Publish HTML Report') {
            step([$class: 'PublishHTMLPublisher', 
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'target/site',
                reportFiles: 'spotbugs.html',
                reportName: 'SpotBugs Report'
            ])
        }
    }
