pipeline {
    agent any

    stages {
        stage('git checkout') {
              steps {
                checkout scmGit(branches: [[name: 'main']], extensions: [], userRemoteConfigs: [[credentialsId: 'Harshit-Github-PAT', url: 'https://github.com/CodeOps-Hub/Terraform-modules.git']])
              }
        }
        stage('Terraform init') {
            steps {
                script{
                    sh '''
                        cd wrapperCode/Network-Skeleton-Wrapper-Code/Dev-Network-Skeleton-Wrapper-Code/
                        terraform init
                    '''                    
                }
                
            }
        }
        stage('Terraform plan') {
            steps {
                withAWS(credentials: 'HARSHIT_AWS_CREDS') {
                    script{
                        sh '''
                            cd wrapperCode/Network-Skeleton-Wrapper-Code/Dev-Network-Skeleton-Wrapper-Code/
                            terraform plan
                        '''                    
                    }
                }
            }
        }
        stage('Approval Stage') {
            steps {
                input 'Do you want to apply Terraform plan?'
            }
        }
        stage('Terraform apply') {
            steps {
                withAWS(credentials: 'HARSHIT_AWS_CREDS') {
                    script{
                        sh '''
                            cd wrapperCode/Network-Skeleton-Wrapper-Code/Dev-Network-Skeleton-Wrapper-Code/
                            terraform apply --auto-approve
                        '''                    
                    }
                }
            }
        }

    }
}
