pipeline {
    agent any
    
    parameters {
        string(name: 'GIT_URL', defaultValue: 'https://github.com/CodeOps-Hub/Ansible.git', description: 'Git repository URL')
        string(name: 'GIT_CREDENTIALS', defaultValue: 'khushi_github_cred', description: 'Git credentials ID')
        string(name: 'GIT_BRANCH', defaultValue: 'Khushi/Attendance-node-exporter', description: 'Git branch to checkout')
        string(name: 'PLAYBOOK_PATH', defaultValue: 'roles/Attendance-node-exporter/playbook.yml', description: 'Path to the playbook file')
    }

    stages ('Clone') {
        script {
            git branch: "${params.GIT_BRANCH}", credentialsId: "${params.GIT_CREDENTIALS}", url: "${params.GIT_URL}"
        }
    } // <-- Missing closing curly brace for 'stages ('Clone')' block
        
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Clone the repository with specified branch
                    sh "git clone -b ${params.GIT_BRANCH} ${params.GIT_URL} ."
                }
            }
        }

        stage('Ansible Run Stage') {
            steps {
                script {
                    // Run the ansible playbook
                    sh "ansible-playbook ${params.PLAYBOOK_PATH}"
                }
            }
        }               
    }
}
