@Library("my-shared-library") _
// testing  webhook-001

// testing  salary CI webhook-001
def Attandance_CI = new org.avengers.template.python.Attandance_CI.attandanceCI.groovy()
    
node {
    
    def url = 'https://github.com/CodeOps-Hub/attendance-api.git'
    def branch = 'main'
    def creds = 'vikram445'    
    def depVersion = '9.0.9'


   Attandance_CI.call(branch: branch,url: url, creds: creds, depVersion: depVersion)
   
    }
