@Library("shared_library") _

def dpcheck = new org.avengers.template.java.dependencyCheck()

node {
    
    def url = 'https://github.com/CodeOps-Hub/p7-salary-API.git'
    def branch = 'main'
    def creds = 'vyadavP7'
    
    dpcheck.call(url, creds, branch)
}
