@Library("shared_library") _

def dpcheck = new org.avengers.template.java.dependencyCheck()

node {
    
    def url = 'https://github.com/vyadavP7/Salary-API.git'
    def branch = 'main'
    def credentialsId = 'vyadavP7'
    
    dpcheck.call(branch: branch,url: url, credentialsId: credentialsId)
    
}
