@Library('p7-shared-library@Vidhi/terragrunt-sharedlib') _

def terragrunt = new org.avengers.template.terragrunt.terragrunt()
properties([
    parameters([
        choice (choices: ['apply', 'destroy'], name: 'action', description: 'Choose Terragrunt ACTION to perform'),
        string (defaultValue: 'vikram/redis_dev', description: '', name: 'branch'),
        string (defaultValue: 'Dev', description: 'define path of root directory', name: 'rootPath'),
        string (defaultValue: 'Redis', description: 'define path of child directory', name: 'childPath'),
    ])
])
node {
    def url = 'https://github.com/CodeOps-Hub/Terragrunt.git'
    def creds = 'harshit-github-token'

// with aws(credentials: 'vikram aws') {
//                         terragrunt.call(url, creds, params.branch, params.rootPath, params.childPath, params.action)
// }
     
     terragrunt.call(url, creds, params.branch, params.rootPath, params.childPath, params.action)
}
