@Library('my_shared_liabrary') _

def terragrunt = new org.avengers.template.terragrunt.terragrunt()
properties([
    parameters([
        choice (choices: ['apply', 'destroy'], name: 'action', description: 'Choose Terragrunt ACTION to perform'),
        string (defaultValue: 'samir/Dev-Scylla', description: '', name: 'branch'),
        string (defaultValue: 'Dev', description: 'define path of root directory', name: 'rootPath'),
        string (defaultValue: 'Scylla', description: 'define path of child directory', name: 'childPath'),
    ])
])
node {
    def url = 'https://github.com/CodeOps-Hub/Terragrunt.git'
    def creds = 'Samir-PT'


     terragrunt.call(url, creds, params.branch, params.rootPath, params.childPath, params.action)
}
