@Library('snaatak-p7') _
def ansible_CI = new org.avengers.template.ansible_CI.ansibleCI()

node {
    
    def url = 'https://github.com/CodeOps-Hub/Jenkins-Playbook.git'
    def creds = '890c8a72-7383-4986-8573-519aacdeb7d2'
    def branch = 'main'
    def gitleaksVersion = '8.18.2'
    def tagVersion = '1.0'
    def path = '/var/lib/jenkins/workspace/Ansible_CD/jenkins_playbook/install_debian.yml'
    
    ansible_CI.call(url, creds, branch, gitleaksVersion, tagVersion, path)
    
}
