@Library('snaatak-p7') _
def dast = new org.avengers.template.python.PythonDast()


node {
    
    def url = 'https://github.com/OT-MICROSERVICES/attendance-api.git'
    def creds = '890c8a72-7383-4986-8573-519aacdeb7d2'
    def branch = 'main'
    def zapVersion = '2.14.0'
    
    dast.call(url, creds, branch, zapVersion)
    
}
