node {
    try {
        stage('Clone Repository') {
            git branch: 'main', url: 'https://github.com/vyadavP7/Salary-API.git'
        }

        stage('Package Artifacts') {
            sh 'mvn clean package -DskipTests=true'
        }

        stage('Owasp DP-Check') {
            dependencyCheck additionalArguments: '--scan target/ --format ALL', odcInstallation: 'DP-check'
        }
    } catch (Exception e) {
        echo 'DP check Failed !'
    } finally {
        archiveArtifacts artifacts: '**/dependency-check-report.html'
        sh "ls ${WORKSPACE}"
        echo 'DP check Successful !'

        sh 'tree ${WORKSPACE}'
    }
}
